name: Crawl casting jobs

on:
  schedule:
    - cron: "0 * * * *"   # hver hele time
  workflow_dispatch: {}    # kan også startes manuelt

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run crawler
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID:  ${{ secrets.GOOGLE_CSE_ID }}
        run: node scripts/crawl.cjs
      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add radar/jobs/live/jobs.json
          git diff --cached --quiet || git commit -m "data(jobs): update jobs.json"
          git push
