name: Crawl casting jobs

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install node-fetch@2
      - name: Run crawler
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        run: node scripts/crawl.mjs
      - name: Commit & push results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/jobs.json
          git commit -m "data(jobs): update jobs.json" || echo "No changes"
          git push
