name: Crawl casting jobs

on:
  schedule:
    - cron: "0 */6 * * *"   # Kører hver 6. time
  workflow_dispatch:        # Tillader manuel kørsel

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run crawler
        run: node scripts/crawl.mjs
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}

      - name: Commit & push results
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/live/jobs.json
          git commit -m "Update jobs.json" || echo "No changes"
          git push
