name: Crawl jobs

on:
  schedule:
    - cron: "0 * * * *"   # kør hver time
  workflow_dispatch:       # mulighed for at starte manuelt

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Run crawler
        run: node scripts/crawl.mjs
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add radar/jobs/live/jobs.json
          git commit -m "data(jobs): update jobs.json" || echo "No changes"
          git push
