name: Crawl casting jobs

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # så vi kan pull’e hele historikken

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run crawler
        run: node scripts/crawl.mjs
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add radar/jobs.json
          git commit -m "data(jobs): update jobs.json" || echo "No changes"
          git push
