name: Crawl casting jobs

on:
  schedule:
    - cron: "0 */6 * * *"   # kør hver 6. time
  workflow_dispatch:        # mulighed for manuel kørsel

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run crawler
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        run: node scripts/crawl.mjs

      - name: Commit & push results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/jobs.json
          git commit -m "data(jobs): update jobs.json"
          git push
